### ISSUE TITLE
Could we avoid parsing the incoming data without the real need?

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/cifplayer#16]
https://github.com/tilde-lab/cifplayer/blob/dac4ed2999fe2ac2464b70cf8d630e6d077cfea5/src/js/app/main.js#L558

**Comment by blokhin** [comment]
@stan-donarise @nin-jin please could you have a look?

**Comment by nin-jin** [comment]
А кто посылает это сообщение? Тут по хорошему надо поменять формат сообщений, так как сообщения могут приходить самые разные от разных источников и их надо как-то отличать.

**Comment by stan-donarise** [comment]
Now matinfo gets 2 args:
`data` - can be either a string or an object. 
`format` - can be omitted, then it will be auto-detected.
https://github.com/stan-donarise/cifplayer/blob/mol/matinfio/matinfio.web.ts#L89

So if the format is an OPTIMADE object, there is no redudant stringify/parse.
