### ISSUE TITLE
Atoms are neither translated nor recreated by symmetry

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/cifplayer#2]

**Comment by aglie** [comment]
Also, Cif is very flexible in how the symmetry can be defined. This could be either the list of elements (like -x,-y,-z), but also International Tables group number andHerman-Mauguin symbols are allowed and ideally all should work.

**Comment by blokhin** [comment]
It's more robust to handle space group number or symbol. Anyway it's always there in any CIF. The disadvantage is that the info for all 230 groups should be stored inside the code, which is a bloat.

**Comment by blokhin** [comment]
@stan-donarise @nin-jin do you think it's doable? Seems to be not so easy thing :disappointed:

**Comment by nin-jin** [comment]
And what is the size of this info in bytes?

**Comment by blokhin** [comment]
@nin-jin here is it https://gitlab.com/ase/ase/-/blob/master/ase/spacegroup/spacegroup.dat (200 Kb)

**Comment by nin-jin** [comment]
It's only 8kb in compressed form, but I'd still rather load it as a separate file.

**Comment by blokhin** [comment]
Addressed by `v1.0.0`
