### ISSUE TITLE
Symmetry icon should only be displayed if symmetry info is present, otherwise not shown

### ISSUE THREAD

**Issue by blokhin** [tilde-lab/cifplayer#26]
Suggested code for https://github.com/tilde-lab/cifplayer/blob/master/player/player.view.web.ts#L469 does not work, symmetry icon is never shown, even for those structures which actually do contain symmetry.

```
if( !this.structure_3d_data().cell_matrix ) return []

return [
  this.Info(), 
  ... this.symlabel() ? [ this.Symlabel() ] : [],
  this.Center(),
]
```

**Comment by stan-donarise** [comment]
Question related to this issue:
Is it correct that the symlabel hidden when mpds_data==true?
https://github.com/tilde-lab/cifplayer/blob/mpds/src/js/app/main.js#L179

**Comment by blokhin** [comment]
@stan-donarise yes, correct, please, let's keep it.
