### ISSUE TITLE
Orbiting directions are wrong

### ISSUE THREAD

**Issue by aglie** [tilde-lab/cifplayer#6]
The rotation of the structure (orbiting) works strangely:
- left-right correctly rotates the axis and atom positions, though the spheres representing atoms turn the other way
- up-down rotation is flipped
- rotation around z axis is flipped

**Comment by blokhin** [comment]
Indeed. Probably, i messed up with Three.js camera. Will have a look.

**Comment by blokhin** [comment]
@aglie i hope, it is more usable now
